PImage red,blue,yellow,green;
PImage gameover,backscreen,gameclear;
ArrayList<Float> rBlocks;
ArrayList<Float> bBlocks;
ArrayList<Float> gBlocks;
ArrayList<Float> yBlocks;
Float temp; 
int speed;
PrintWriter map;
String[] lines;
String k; 
float v;
int blockWidth = 100;
int blockHeight = 50;
int line1 = 100;
int line2 = 200;
int line3 = 300;
int line4 = 400;
ArrayList<Float> rNotes;
ArrayList<Float> gNotes;
ArrayList<Float> bNotes;
ArrayList<Float> yNotes;
boolean rPressed = false; 
boolean gPressed = false;
boolean bPressed = false; 
boolean yPressed = false;
int r_time = 0; 
int g_time = 0; 
int b_time = 0; 
int y_time = 0;
int judge = 0;
int gameState = 1;
