PImage B1; PImage B2; PImage B3; PImage B4;
ArrayList<Float> rBlocks;
ArrayList<Float> bBlocks;
ArrayList<Float> gBlocks;
ArrayList<Float> yBlocks;
Float temp; 
int speed;
PrintWriter map;
String[] lines;
String k; 
float v;
int blockWidth = 100;
int blockHeight = 50;
int line1 = 100;
int line2 = 200;
int line3 = 300;
int line4 = 400;
